
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1082x691")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 691,
    width = 1082,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    322.0,
    0.0,
    1082.0,
    691.0,
    fill="#272C30",
    outline="")

canvas.create_rectangle(
    343.0,
    23.0,
    1061.0,
    669.0,
    fill="#272C30",
    outline="")

canvas.create_text(
    343.0,
    23.0,
    anchor="nw",
    text="Título\n",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    322.0,
    691.0,
    fill="#272C30",
    outline="")

canvas.create_text(
    57.0,
    99.0,
    anchor="nw",
    text="Distribuidora\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    44.0,
    154.0,
    anchor="nw",
    text="Desenvolvedor",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    0.0,
    22.0,
    anchor="nw",
    text="STEAM GAMES\n",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    29.0,
    211.0,
    anchor="nw",
    text="Melhores Jogos\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
