
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\User\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1082x691")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 691,
    width = 1082,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    322.0,
    0.0,
    1082.0,
    691.0,
    fill="#272C30",
    outline="")

canvas.create_rectangle(
    340.0,
    16.0,
    1072.0,
    674.0,
    fill="#272C30",
    outline="")

canvas.create_text(
    991.0,
    231.0,
    anchor="nw",
    text="preço",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    991.0,
    175.0,
    anchor="nw",
    text="preço",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    810.0,
    175.0,
    anchor="nw",
    text="Distribuidora\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    779.0,
    234.0,
    anchor="nw",
    text="Distribuidora\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    501.0,
    231.0,
    anchor="nw",
    text="tittle",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    612.0,
    175.0,
    anchor="nw",
    text="Desenvolvedor",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    501.0,
    175.0,
    anchor="nw",
    text="tittle",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    0.0,
    25.0,
    333.0,
    81.0,
    fill="#000000",
    outline="")



canvas.create_rectangle(
    0.0,
    0.0,
    322.0,
    691.0,
    fill="#272C30",
    outline="")

canvas.create_text(
    59.0,
    209.0,
    anchor="nw",
    text="Distribuidora\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    46.0,
    264.0,
    anchor="nw",
    text="Desenvolvedor",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    581.0,
    234.0,
    anchor="nw",
    text="Desenvolvedor",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    0.0,
    22.0,
    anchor="nw",
    text="STEAM GAMES\n",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    31.0,
    321.0,
    anchor="nw",
    text="Melhores Jogos\n",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

x1, y1, x2, y2 = 535.0, 59.0, 877.0, 99.0

# Crie um widget Entry no mesmo local que o retângulo original
entry_widget = Entry(
    window,
    bg="#FFFFFF",  # Fundo branco
    fg="#000000",  # Texto preto
    font=("Inter", 20 * -1),  # Configurações da fonte
    bd=0,  # Largura da borda
    highlightthickness=0  # Sem destaque
)

# Crie o widget Entry no canvas
entry_window = canvas.create_window(
    (x1 + x2) / 2,   # Posição x média
    (y1 + y2) / 2,    # Posição y média
    width=x2 - x1,     # Largura
    height=y2 - y1,    # Altura
    window=entry_widget  # Widget Entry
)



canvas.create_rectangle(
    377.0,
    207.0,
    470.0,
    283.0,
    fill="#000000",
    outline="")

# Crie um widget Button no mesmo local com o texto "Search"
button_widget = Button(
    window,
    text="Search",   # Texto do botão
    bg="#000000",    # Cor de fundo preta
    fg="#FFFFFF",    # Cor do texto branco
    font=("Inter", 20 * -1),  # Configurações da fonte
    bd=0,            # Largura da borda
    highlightthickness=0,  # Sem destaque
)

# Crie o widget Button no canvas
button_window = canvas.create_window(
    887.0,           # Posição x
    67.0,            # Posição y
    anchor="nw",     # Ancoragem no canto superior esquerdo
    window=button_widget  # Widget Button
)
canvas.create_text(
    377.0,
    175.0,
    anchor="nw",
    text="Banner",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
